"""initial schema

Revision ID: 4ef773f3345a
Revises: 
Create Date: 2026-09-30 12:04:27.163948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4ef773f3345a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributed_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=100), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.String(length=500), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bedrock_request_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failed', 'degraded', 'blocked')", name='ck_call_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributed_calls_created_at'), 'attributed_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_attributed_calls_customer_id'), 'attributed_calls', ['customer_id'], unique=False)
    op.create_index(op.f('ix_attributed_calls_decision_id'), 'attributed_calls', ['decision_id'], unique=False)
    op.create_index('ix_calls_customer_created', 'attributed_calls', ['customer_id', 'created_at'], unique=False)
    op.create_index('ix_calls_system_decision_created', 'attributed_calls', ['system', 'decision_type', 'created_at'], unique=False)
    op.create_table('budget_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('system', sa.String(length=100), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('spent_today', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('ceiling', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('hard_stop', 'degrade', 'calendar_override_applied', 'fail_open', 'fail_closed')", name='ck_event_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_events_occurred_at'), 'budget_events', ['occurred_at'], unique=False)
    op.create_table('customer_accounts',
    sa.Column('canonical_id', sa.UUID(), nullable=False),
    sa.Column('display_label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('canonical_id')
    )
    op.create_table('decision_type_configs',
    sa.Column('system', sa.String(length=100), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('enforcement_mode', sa.String(length=20), nullable=False),
    sa.Column('daily_ceiling', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fallback_model_id', sa.String(length=200), nullable=True),
    sa.Column('routing_model_id', sa.String(length=200), nullable=False),
    sa.Column('reservation_estimate', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("enforcement_mode != 'degrade' OR fallback_model_id IS NOT NULL", name='ck_degrade_requires_fallback'),
    sa.CheckConstraint("enforcement_mode IN ('hard_stop', 'degrade')", name='ck_enforcement_mode'),
    sa.PrimaryKeyConstraint('system', 'decision_type')
    )
    op.create_table('rate_card_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_rate_per_million', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('output_rate_per_million', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cache_write_multiplier', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('cache_read_multiplier', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_card_entries_model_id'), 'rate_card_entries', ['model_id'], unique=False)
    op.create_index('ix_rate_card_model_effective', 'rate_card_entries', ['model_id', 'effective_from'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('usage_type', sa.String(length=100), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('gap_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_start', 'period_end', 'model_id', 'usage_type', name='uq_reconciliation_period')
    )
    op.create_table('ceiling_calendar_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('system', sa.String(length=100), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('override_date', sa.Date(), nullable=False),
    sa.Column('ceiling', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system', 'decision_type'], ['decision_type_configs.system', 'decision_type_configs.decision_type'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system', 'decision_type', 'override_date', name='uq_calendar_override')
    )
    op.create_table('customer_identifiers',
    sa.Column('system', sa.String(length=100), nullable=False),
    sa.Column('raw_identifier', sa.String(length=500), nullable=False),
    sa.Column('canonical_id', sa.UUID(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['customer_accounts.canonical_id'], ),
    sa.PrimaryKeyConstraint('system', 'raw_identifier')
    )
    op.create_index(op.f('ix_customer_identifiers_canonical_id'), 'customer_identifiers', ['canonical_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_identifiers_canonical_id'), table_name='customer_identifiers')
    op.drop_table('customer_identifiers')
    op.drop_table('ceiling_calendar_overrides')
    op.drop_table('reconciliation_runs')
    op.drop_index('ix_rate_card_model_effective', table_name='rate_card_entries')
    op.drop_index(op.f('ix_rate_card_entries_model_id'), table_name='rate_card_entries')
    op.drop_table('rate_card_entries')
    op.drop_table('decision_type_configs')
    op.drop_table('customer_accounts')
    op.drop_index(op.f('ix_budget_events_occurred_at'), table_name='budget_events')
    op.drop_table('budget_events')
    op.drop_index('ix_calls_system_decision_created', table_name='attributed_calls')
    op.drop_index('ix_calls_customer_created', table_name='attributed_calls')
    op.drop_index(op.f('ix_attributed_calls_decision_id'), table_name='attributed_calls')
    op.drop_index(op.f('ix_attributed_calls_customer_id'), table_name='attributed_calls')
    op.drop_index(op.f('ix_attributed_calls_created_at'), table_name='attributed_calls')
    op.drop_table('attributed_calls')
    # ### end Alembic commands ###
