"""rate card unique constraint

Revision ID: bece26be48a1
Revises: 4ef773f3345a
Create Date: 2026-09-30 12:20:24.902938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bece26be48a1'
down_revision: Union[str, None] = '4ef773f3345a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_card_model_effective'), table_name='rate_card_entries')
    op.create_unique_constraint('uq_rate_card_model_effective', 'rate_card_entries', ['model_id', 'effective_from'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_rate_card_model_effective', 'rate_card_entries', type_='unique')
    op.create_index(op.f('ix_rate_card_model_effective'), 'rate_card_entries', ['model_id', 'effective_from'], unique=False)
    # ### end Alembic commands ###
